### ISSUE TITLE
After installing, strapi won't start

### ISSUE THREAD

**Issue by matibaski** [TonyDeplanque/strapi-plugin-migrations#6]
After installing this plugin with strapi `v4.1.12` it won't start (using node `16.15.0`, npm `8.10.0`, yarn `1.22.18`).

Following error appears:

```
[2022-06-01 00:03:34.587] error: The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at join (node:path:1172:7)
    at Object.loadPlugins (/opt/node_modules/@strapi/strapi/lib/core/loaders/plugins/index.js:89:34)
    at async Strapi.loadPlugins (/opt/node_modules/@strapi/strapi/lib/Strapi.js:290:5)
    at async Promise.all (index 2)
    at async Strapi.register (/opt/node_modules/@strapi/strapi/lib/Strapi.js:326:5)
    at async Strapi.load (/opt/node_modules/@strapi/strapi/lib/Strapi.js:425:5)
    at async Strapi.start (/opt/node_modules/@strapi/strapi/lib/Strapi.js:169:9)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My config:
```
// config/plugins.js
'migrations': {
  enabled: true,
  config: {
    autoStart: true,
    migrationFolderPath : 'migrations'
  },
},
```

I basically copy pasted the file `v1_edit_reset_password_url.js` into `migrations/`

Anyone else has this problem? 
When disabling the plugin (`enabled: false`) my strapi starts correctly.

**Comment by gabrieljmj** [comment]
Same problem!

**Comment by Kadreev** [comment]
Hey guys, the same issue - just install the plugin 
`yarn add strapi-plugin-migrations`
and run `yarn build && yarn develop`

Don't forget to reset the state of the migrations folder to be empty and enable the plugin

That's how I resolved the issue.
